FROM soulter/astrbot:latest
WORKDIR /AstrBot

COPY . /AstrBot/

RUN uv pip install -r requirements.txt --no-cache-dir --system
RUN uv pip install socksio uv pyffmpeg pilk --no-cache-dir --system

EXPOSE 6185
EXPOSE 6186

CMD [ "python", "main.py" ]



